Repository snek-at/client, pull requests merged in 2020-05, with the labels that each got.

#13 Add basics 1 to implement 1
  .gitignore
  .npmignore
  package.json
  public/index.html
  public/manifest.json
  src/apollo/index.js
  src/endpoints/apollo.ts
  src/endpoints/index.ts
  src/endpoints/scraper.ts
  src/index.js
  src/index.ts
  src/session/cookie-utils.ts
  src/session/index.ts
  src/session/sessions.ts
  src/templates/index.ts
  src/templates/snek/gql/index.ts
  src/templates/snek/gql/mutations/index.ts
  src/templates/snek/gql/mutations/jwtAuth.ts
  src/templates/snek/gql/mutations/user.ts
  src/templates/snek/gql/queries/general.ts
  src/templates/snek/gql/queries/index.ts
  src/templates/snek/gql/queries/user.ts
  src/templates/snek/gql/routines/index.ts
  src/templates/snek/gql/tasks/auth.ts
  src/templates/snek/gql/tasks/general.ts
  src/templates/snek/gql/tasks/index.ts
  src/templates/snek/gql/tasks/user.ts
  src/templates/snek/index.ts
  src/templates/snek/rest/index.ts
  test.js
  tsconfig.json
Labels: documentation, enhancement

#18 Adjust config 1 to implement 1
  .vscode/settings.json
  package.json
  tsconfig.json
Labels: bug, documentation, enhancement, invalid

#21 Improve client 1 to implement 1
  src/index.ts
Labels: bug, enhancement

#23 Improve scraper 1 to implement 1
  src/endpoints/index.ts
  src/endpoints/scraper.ts
Labels: enhancement

#25 Improve client 2 to implement 1
  src/index.ts
Labels: bug, invalid

#31 Glitch 1 to implement 1
  package.json
  src/endpoints/apollo.ts
  src/endpoints/scraper.ts
  src/session/cookie-utils.ts
  src/session/index.ts
  src/session/sessions.ts
  src/templates/snek/gql/errors.ts
  src/templates/snek/gql/tasks/auth.ts
  src/templates/snek/gql/tasks/general.ts
  src/templates/snek/gql/tasks/index.ts
  src/templates/snek/gql/tasks/user.ts
Labels: bug, enhancement, invalid

#34 Improve documentation 1 to implement 1
  .vscode/settings.json
  src/endpoints/apollo.ts
  src/endpoints/index.ts
  src/endpoints/scraper.ts
  src/index.ts
  src/session/index.ts
  src/session/sessions.ts
  src/templates/index.ts
  src/templates/snek/gql/errors.ts
  src/templates/snek/gql/index.ts
  src/templates/snek/gql/mutations/index.ts
  src/templates/snek/gql/mutations/jwtAuth.ts
  src/templates/snek/gql/mutations/user.ts
  src/templates/snek/gql/queries/general.ts
  src/templates/snek/gql/queries/index.ts
  src/templates/snek/gql/queries/user.ts
  src/templates/snek/gql/tasks/auth.ts
  src/templates/snek/gql/tasks/general.ts
  src/templates/snek/gql/tasks/index.ts
  src/templates/snek/gql/tasks/user.ts
  src/templates/snek/index.ts
Labels: documentation

#36 Update pr template a1 to master
  PULL_REQUEST_TEMPLATE
Labels: documentation

#41 Improve client b1 to implement 1
  src/endpoints/apollo.ts
  src/endpoints/index.ts
  src/endpoints/scraper.ts
  src/index.ts
  src/session/index.ts
  src/session/sessions.ts
  src/templates/snek/gql/errors.ts
  src/templates/snek/gql/index.ts
  src/templates/snek/gql/tasks/auth.ts
  src/templates/snek/gql/tasks/general.ts
  src/templates/snek/gql/tasks/index.ts
  src/templates/snek/gql/tasks/user.ts
Labels: enhancement

#5 Readme patch 1 to implement 1
  README.md
Labels: documentation

#42 schettn patch 1 to implement 1
  README.md
Labels: documentation
